---
- name: Ping hosts Playbook
  hosts: localhost
  gather_facts: no
  vars:
    target_url: "localhost"  # Change this to your desired URL

  tasks:
    - name: Ping all managed nodes
      ansible.builtin.ping:
    - name: Display the response content
      debug:
        var: ping_result.content
      register:
        ping_result
    # - name: Check if the ping was successful
    #   assert:
    #     that:
    #       - ping_result.status == 200
    #     fail_msg: "The URL {{ target_url }} returned a status code other than 200."
