---
- name: Ping hosts Playbook
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tasks:
    - name: Ping all managed nodes
      ansible.builtin.ping:
    - name: Display the response content
      debug:
        var: ping_result.content
      register:
        ping_result
